### ISSUE TITLE
No rule for creating target 'Logger.o' needed by /projects/lgpt.rpi-exe"

### ISSUE THREAD

**Issue by mackemint** [Mdashdotdashn/LittleGPTracker#7]
Hey!
I'm getting the above error message when attempting to compile for Raspberry Pi. I wanted to try to use jack_client_open instead of the deprecated jack_client_new, but this error message showed up when using the makefile before changing any code.
Also, it seems like the $(PWD) command in the makefile isn't supported, and had to be changed to $(shell PWD).

**Comment by mre-ableton** [comment]
Which distribution do you use on your raspberry pi ?

**Comment by mackemint** [comment]
I'm running Raspbian Jessie.

**Comment by mackemint** [comment]
Solved by running "make" instead of "sudo make". Go figure, the $(PWD) envvar doesn't seem to work the same way when running make as sudo. Sudo su before running make works too.

This produced the following errors: 

> SampleInstrument.cpp:29:1: error: narrowing conversion of '-1' from 'int' to 'char' inside { }
Which was fixed by initializing lastMidiNote_ as "signed char" instead of the char type it is today.
This needs to be done in SampleInstrument.cpp and SampleInstrument.h
